version: 2.1

jobs:
  checkoutAndTest:
    docker:
      - image: cimg/node:17.4.0
    steps:
      - checkout
      - run: cd ..
      - run: cd TVCRA_Bingo
      - run: cd bingo-app
      - run: node --version
      - run: npm --version
      - run: npm install
      - run: npm run test
workflows:
  build:
    jobs:
      - checkoutAndTest
